language: cpp
os: linux
dist: bionic
sudo: required

jobs:
  include:
  - env: G4VER=10.5.1
  - env: G4VER=10.6.1

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    update: true
    packages:
      - libxerces-c3.2
      - libxerces-c-dev
      - expat
      - libexpat1-dev
      - assimp-utils
      - libassimp-dev
      - libassimp-doc
      - libassimp4
      #- libtet1.5
      #- libtet1.5-dev
      #- tetgen
      - gcc-9
      - g++-9

before_install:
  - CC=gcc-9 && CXX=g++-9

install:
  - wget https://www.ikp.uni-koeln.de/~jmayer/github/geant4_${G4VER}_amd64.deb
  - sudo dpkg -i geant4_${G4VER}_amd64.deb
  - source /usr/bin/geant4.sh

script:
  - ./G4Batch.sh
