language: cpp
os: linux
dist: focal
sudo: required

jobs:
  include:
  - env: G4VER=10.5.1
  - env: G4VER=10.6.3
  - env: G4VER=10.7.1

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    update: true
    packages:
      - libxerces-c-dev
      - libexpat-dev
      - assimp-utils
      - libassimp-dev
      - libassimp-doc
      - libassimp5
      #- libtet1.5
      #- libtet1.5-dev
      #- tetgen
      - gcc-10
      - g++-10

before_install:
  - CC=gcc-10 && CXX=g++-10

install:
  - wget https://www.ikp.uni-koeln.de/~jmayer/public/geant4/geant4_${G4VER}_amd64.deb
  - sudo dpkg -i geant4_${G4VER}_amd64.deb
  - source /usr/bin/geant4.sh

script:
  - ./G4Batch.sh
